### ISSUE TITLE
Update the pipeline when handel-codepipeline file changes

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/handel-codepipeline#110]
I don't know how feasible it is, but it would be nice if the handel-codepipeline file changes that the pipeline gets updated instead of just using the previously created pipeline.

**Comment by dsw88** [comment]
Given the nature of this tool, this probably isn't possible to implement directly here. Outside of the tool, events could be implemented that re-run the pipeline update action, but that would have to be done inside whatever account is using this tool.
