### ISSUE TITLE
Problem caused by caching

### ISSUE THREAD

**Issue by jvisker** [byu-oit/handel-codepipeline#119]
When I was trying to deploy I misspelled the path to my account config. After that the bad account config was cached and caused an error every time I tried to deploy. I now know that there is a file caching that information so that it can be changed or deleted. However, I think that it would be a good idea to include that in the documentation and/or create a new command that can clear the cache if desired.

**Comment by dsw88** [comment]
This was implemented in Rockefeller, which is the eventual replacement for Handel-CodePipeline: https://github.com/byu-oit/rockefeller/commit/f1a4e504c96d66215a6d9afb46ec66a672f8e97d
