### ISSUE TITLE
Automatically create and close Standard RFCs in ServiceNow for production deployments

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel-codepipeline#22]
Creating Standard RFCs for automated production deployments is required by OIT's Change Management policy.  Automating it in handel will make this trivially easy for OIT developers to comply with that policy. 

There is python code already written that does this [here](https://github.com/byu-oit-appdev/pipeline-scripts/blob/master/rfc.py).

Note, the Standard RFC must be started right before the actual deployment phase and then completed right after deployment is finished recording the start & stop times of the deployment and if the deployment succeeded or failed.

I can walk the developer assigned to this through the whole process and the OIT Tools team developers can answer any ServiceNow questions I can't.

**Comment by pauldeden** [comment]
I don't know if this would be better implemented in handel instead of handel-codepipeline.  

It could be implemented as CodeBuild phases in handel-codepipeline or as part of the actual handel deployment as well.  

FYI, the developer will need to pass in the Standard Change Template id so the code knows which template to use to create the Standard Change from.

**Comment by dsw88** [comment]
I implemented the Invoke Lambda phase type, which is one part of this work: http://handel-codepipeline.readthedocs.io/en/latest/phase-types/invoke_lambda.html. We'll put Lambdas in our accounts that we can invoke to perform our RFC process. Those Lambdas aren't there yet, but we'll work to put them there.

**Comment by ndpete** [comment]
@dsw88 @pauldeden Like my comments about slack notify on failed pipelines this has been implemented internally by consuming the Cloudwatch events across all our accounts. Do we still want to implement something as part of handel-codepipeline or close the issue?

**Comment by pauldeden** [comment]
I don’t personally think that implementing it in handle could pipeline is a
requirement. It was just the initial design. If implementing using cloud
which events gives the same result that I think the implementation is done
but like I talked with Jason about I still feel there is more to document.
I’ll be detailing what I think needs to be documented soon.

**Comment by dsw88** [comment]
I agree, this issue can be closed since it was implemented internally in our accounts.
