### ISSUE TITLE
Give the ability for the user to specify rights that CodeBuild needs

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel-codepipeline#38]
The use case is for running tests that call AWS services in the build phase.

Here is an example.  https://github.com/byu-oit-appdev/garage-door-api/blob/master/buildspec.yml#L13  

It calls the AWS IoT service read-only during the tests.

**Comment by dsw88** [comment]
I don't think we want to inject production resources in the build phase (especially since they might not even always be there). I would recommend stubbing out AWS calls during unit tests in a build phase, then having a small suite of acceptance-level tests after the deploy.
