### ISSUE TITLE
Slack me when my pipeline doesn't complete successfully

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel-codepipeline#53]
Most of the time when I push code to handel-codepipeline I want to be able to move on to something else while the pipeline is running.

I would like handel-codepipeline to slack me when there is a problem with a run of the pipeline, otherwise I want to assume all went well.

**Comment by ndpete** [comment]
@dsw88 @pauldeden This has been resolved internally with cloudwatch events for all pipelines (even those created outside of handel-codepipeline) across all accounts. Is this something we are still interested in adding specifically to handel-codepipeline?

**Comment by pauldeden** [comment]
See my response on the duplicate issue

**Comment by dsw88** [comment]
I think eventually when CodePipeline provides good support for this use case, we should implement something in Handel-CodePipeline. Until that time our needs at BYU are definitely met by what we've implemented in our accounts, so I think this issue can be closed.
