### ISSUE TITLE
Tag cloudformation stack

### ISSUE THREAD

**Issue by joshgubler** [byu-oit/handel-codepipeline#59]
I'm not sure if this should be a feature of handel, or handel-codepipeline.

In addition to tagging the resources that are created by a handel phase, it would be nice if the cloudformation stacks were tagged. This way we can quickly see stacks that can be shutdown in dev, know which team to contact about a stack, etc.

**Comment by dsw88** [comment]
This is a Handel feature, so I'm moving this over to Handel in https://github.com/byu-oit/handel/issues/174.
