### ISSUE TITLE
Add two new phase types called 'npmjs.com' and 'pypi'

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel-codepipeline#64]
They would deploy new versions of nodejs and python modules after the automated tests pass.

This would be a simplification and standardization of what is already happening in handel-codepipeline pipelines.  See https://github.com/byu-oit/awslogin/blob/master/buildspec.yml for an example.

The benefit is developers would have a simpler and standard way to deploy nodejs and python modules.

**Comment by dsw88** [comment]
Great idea, I've put this on the roadmap.
