### ISSUE TITLE
Add Handel environment variables to CodeBuild

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/handel-codepipeline#65]
Sometimes our systems, deployed by Handel need access to Handel environment variables during the CodeBuild portion of a Handel-Codepipeline created CI/CD pipeline, usually in the testing phase.

Here is an example of the output of a CodeBuild run that errored out during the tests because the Handel environment variable that gives the name of a dependent Handel DynamoDB service wasn't available.

![screenshot 2017-07-17 at 10 11 10 pm](https://user-images.githubusercontent.com/4304479/28300549-70e43930-6b3d-11e7-87b7-50d7231e588f.png)
 
Here is the line in the handel.yml file that shows the dependency on Dynamo.  https://github.com/pauldeden/fhe-assignment-alexa-skill/blob/master/handel.yml#L17

**Comment by dsw88** [comment]
I don't think this will really be possible to implement. The build phase occurs prior to the deploy phase, so there's no guarantee Handel-deployed resources would even be there.

Additionally, it feels like the build phase should focus on providing support for builds and unit-level tests, not providing access to the deployed production environment. I would recommend stubbing out calls to DynamoDB during unit tests, and then have a smaller suite of acceptance-level tests after deploy.
